name: Generate outputs
on:
  workflow_call:

jobs:
  generate-outputs:
    runs-on: ubuntu-latest
    name: Generate ouputs
    steps:
    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

    - name: Run
      run: |
        chmod -R a+w outputs
        make -C outputs -j $(nproc) DOCKER_RUN_OPTS="-e COLUMNS=94 -e LINES=24"

    - name: Create pull request
      run: gh pr create -B main -H regenerate-outputs --title "Regenerate outputs" --body "Automated update"
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
